### ISSUE TITLE
tests: if postgres is not running, tests segfault

### ISSUE THREAD

**Issue by smola** [src-d/borges#119]
With no Postgres running, there is a test that segfauls.
Tests or suites should check if postgres is running and fail earlier with a proper error.

```
➜  borges git:(7862e25) ✗ go test -v .                                           
=== RUN   TestArchiver
=== RUN   TestArchiver/TestFixtures
=== RUN   TestArchiver/TestFixtures/no_previous_references_and_no_updates
=== RUN   TestArchiver/TestFixtures/one_existing_reference_is_removed_(output_with_no_references)
=== RUN   TestArchiver/TestFixtures/one_existing_reference_is_removed_(output_with_references)
=== RUN   TestArchiver/TestFixtures/one_reference_changes_his_hash
=== RUN   TestArchiver/TestFixtures/all_references_are_new
=== RUN   TestArchiver/TestFixtures/all_references_are_deleted
=== RUN   TestArchiver/TestFixtures/all_references_are_up_to_date
=== RUN   TestArchiver/TestFixtures/all_reference_are_new_except_two_(up_to_date)
=== RUN   TestArchiver/TestFixtures/all_reference_are_new_except_one_(updated)
=== RUN   TestArchiver/TestFixtures/all_reference_are_new_except_one_(updated_with_new_init)
=== RUN   TestArchiver/TestFixtures/all_reference_are_new_except_one_(one_root_removed)
=== RUN   TestArchiver/TestNotExistingRepository
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb4a7e2]

goroutine 58 [running]:
testing.tRunner.func1(0xc4203f31e0)
	/usr/local/go/src/testing/testing.go:622 +0x29d
panic(0xc4f8c0, 0x11f8980)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/src-d/borges.(*ArchiverSuite).TestNotExistingRepository(0xc4200202d0)
	/home/smola/dev/go/src/github.com/src-d/borges/archiver_test.go:163 +0x1e2
reflect.Value.call(0xc4204a4780, 0xc42049c1e0, 0x13, 0xd50ee6, 0x4, 0xc4203a3f80, 0x1, 0x1, 0xc4203a3ec0, 0xd4e180, ...)
	/usr/local/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0xc4204a4780, 0xc42049c1e0, 0x13, 0xc4203a3f80, 0x1, 0x1, 0xbb50a3, 0x19, 0x0)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/src-d/borges/vendor/github.com/stretchr/testify/suite.Run.func2(0xc4203f31e0)
	/home/smola/dev/go/src/github.com/src-d/borges/vendor/github.com/stretchr/testify/suite/suite.go:102 +0x25f
testing.tRunner(0xc4203f31e0, 0xc4204a2500)
	/usr/local/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x2ca
exit status 2
FAIL	github.com/src-d/borges	0.063s
```

**Comment by erizocosmico** [comment]
Fixed by https://github.com/src-d/borges/issues/119
