### ISSUE TITLE
fatal: morestack on g0

### ISSUE THREAD

**Issue by ajnavarro** [src-d/borges#186]
Error on borges consumer: 

```
t=2017-11-22T03:20:25+0000 lvl=dbug msg="repository processed" module=borges worker=8 job=015ec27f-147b-2767-8027-be87576ebdc7 endpoint=git://github.com/dancannon/k8s_dev caller=archiver.go:199
t=2017-11-22T03:20:25+0000 lvl=info msg="job finished successfully" module=borges worker=8 job=015ec27f-147b-2767-8027-be87576ebdc7 caller=archiver.go:82
t=2017-11-22T03:20:25+0000 lvl=info msg="job started" module=borges worker=8 job=015ec27f-14f6-77c5-e291-120393d90e5f caller=archiver.go:76
t=2017-11-22T03:20:25+0000 lvl=dbug msg="repository model obtained" module=borges worker=8 job=015ec27f-14f6-77c5-e291-120393d90e5f status=pending last-fetch=nil references=0 caller=archiver.go:111
fatal: morestack on g0
```

It appears to be that we are creating go routines without finish the previous ones:

https://golang.org/src/runtime/asm_amd64.s Line 367.

**Comment by jfontan** [comment]
Using HTTP to download repositories it spits the following messagest:

```
goroutine 890 [select]:
net/http.(*persistConn).readLoop(0xc42039f440)
	/usr/lib/go-1.9/src/net/http/transport.go:1654 +0x7a7
created by net/http.(*Transport).dialConn
	/usr/lib/go-1.9/src/net/http/transport.go:1186 +0xa2e

goroutine 891 [select]:
net/http.(*persistConn).writeLoop(0xc42039f440)
	/usr/lib/go-1.9/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/lib/go-1.9/src/net/http/transport.go:1187 +0xa53
```

Also the number of goroutines is growing almost constantly.

**Comment by ajnavarro** [comment]
This bug is happening again in some cases.

**Comment by ajnavarro** [comment]
Reopening, It appears again

**Comment by smola** [comment]
Keep an eye on https://github.com/golang/go/issues/23360
Is this reproducible in any environment?
What are Linux kernel versions there?

**Comment by ajnavarro** [comment]
Closing this bug. There is not only one cause for it, we fixed a coupled of them in the past.
