### ISSUE TITLE
Some repositories panic with `cannot get hash`

### ISSUE THREAD

**Issue by jfontan** [src-d/borges#229]
On pushing to rooted repo some repositories panic with `cannot get hash`. For example:

https://github.com/gifnksm/ProjectEulerRust

```
[...]
t=2018-02-03T01:58:28+0000 lvl=dbug msg="repository model obtained" module=borges worker=19 job=01614be7-e05e-4e68-cd33-a345020c55
f8 status=pending last-fetch=nil references=0 caller=archiver.go:111
panic: cannot get hash

goroutine 235062 [running]:
github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*ObjectToPack).Hash(0xc48307f4a0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/object_pack.go:12
7 +0x138
github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*deltaSelector).restoreOriginal(0xc485d26410, 0x
c48307f4a0, 0xc433b81b58, 0x0)
        /home/travis/gopath/src/github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/delta_selector.go
:194 +0x6c
github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Encoder).entry(0xc48d4af8c0, 0xc48307f4a0, 0xc4
21353868, 0x456370)
        /home/travis/gopath/src/github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/encoder.go:90 +0x
28f
github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Encoder).writeBaseIfDelta(0xc48d4af8c0, 0xc43e2
4e240, 0xc43407e600, 0x3)
        /home/travis/gopath/src/github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/encoder.go:138 +0
x5a
github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Encoder).entry(0xc48d4af8c0, 0xc43e24e240, 0x2,
 0x2)
        /home/travis/gopath/src/github.com/src-d/borges/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/encoder.go:100 +0
x5d
[...]
```

**Comment by jfontan** [comment]
Fix in: https://github.com/src-d/go-git/pull/744

**Comment by erizocosmico** [comment]
@jfontan if you put "Closes #FOO" or "Fixes #FOO" in the description of the PR this gets closed automatically when it's merged (and is back-referenced)
